### ISSUE TITLE
use rand::sample

### ISSUE THREAD

**Issue by ConnyOnny** [katecpp/RustPlayground#1]
the get_random_line function could be simpler if it would make use of the <a href="https://doc.rust-lang.org/rand/rand/fn.sample.html">rand::sample function</a>

**Comment by katecpp** [comment]
Solution implemented.

**Comment by ConnyOnny** [comment]
Nice :-) Note that this also reduces the memory requirements of the application, as the words file is not kept in memory as a whole anymore.

**Comment by katecpp** [comment]
That's true, it's a big improvement :). Thanks for advice!
